apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["sh", "-c", "echo Secret Vars:; env | grep DB_; sleep 3600"]
      envFrom:
        - secretRef:
            name: app-secret
