apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: web
    env: dev
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 80
